### ISSUE TITLE
Contributions 

### ISSUE THREAD

**Issue by dinegri** [university-of-auckland/kafka-http-sink-connector#2]
Hi, I would like to contribute to your project, but before I would like to know if this project is active

**Comment by ndreno** [comment]
Hi there,

Yes we are still using it at uoa, @kedarkrishnan to confirm code base is still up to date! 👍 
Feel free to make a PR for us to review

**Comment by danieljimeneznz** [comment]
@tksd123 once the code is confirmed up to date, I might see about looking at what is required in the changes for #1

**Comment by ndreno** [comment]
Hey guys, now the code is up to date!! Feel free to contribute via PR :)
