### ISSUE TITLE
Repository License

### ISSUE THREAD

**Issue by ecnaidar** [university-of-auckland/kafka-http-sink-connector#6]
Hello, currently looking at implementations of Kafka Connectors HTTP sinks and yours seems to be a solid option.
I would like to use/fork it for one of the tasks in my organisation, however there is no licence available for repository and per [Github policies](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) it is considered to be a proprietary code that disallows such usage.

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. 

Would it be possible for one of the maintainers to clarify that it is indeed possible to use your project and if possible add license of choice to repository so that there is no misunderstandings regarding it.
Thank you!

**Comment by jomach** [comment]
+1

**Comment by kedarkrishnan** [comment]
Thanks for pointing it out. I  will work with the team to get the license updated.

**Comment by jomach** [comment]
any news here ?

**Comment by kedarkrishnan** [comment]
We have added MIT license to the repo.
